import type { Metadata } from 'next'
import { Rubik as Font } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/header'

const font = Font({
  variable: '--font-sans',
  subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body
        className={`${font.variable} ${font.variable} font-sans antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
